{% set name = "sqlglot" %}
{% set version = "23.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglot-{{ version }}.tar.gz
  sha256: b740c168baa19e5c47bfa8544ae3d829751a05bb6ac01b49bc6ec306101320f8

build:
  number: 0
  noarch: python

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps --no-build-isolation -vv
      noarch: python

    requirements:
      host:
        - pip
        - python >=3.7
        - setuptools_scm
      run:
        - python >=3.7

    test:
      source_files:
        - tests
      imports:
        - sqlglot
      commands:
        - pip check
        - pytest -vvv --capture=tee-sys tests
      requires:
        - pip
        - openjdk
        - pandas
        - pyspark
        - pytest
        - python-dateutil

  - name: {{ name }}-rs
    build:
      script: echo Nothing to do.
      noarch: python

    requirements:
      host:
        - pip
        - python >=3.7
        - setuptools_scm
      run:
        - python >=3.7
        - {{ pin_subpackage('sqlglot', exact=True) }}
        - sqlglotrs

    test:
      source_files:
        - tests
      imports:
        - sqlglot
      commands:
        - pip check
        - pytest -vvv --capture=tee-sys -k tests
      requires:
        - pip
        - openjdk
        - pandas
        - pyspark
        - pytest
        - python-dateutil
        - python-duckdb >=0.6

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
