{% set name = "sqlglot" %}
{% set version = "22.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglot-{{ version }}.tar.gz
  sha256: a323fa34ceae3cbe3ae1cedbbbe6e39dcda8332f66daa03c23bda267275e1fa7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - python >=3.7

test:
  source_files:
    - tests
  imports:
    - sqlglot
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - openjdk
    - pip
    - pandas
    - pyspark
    - pytest
    - python-dateutil
    - python-duckdb >=0.6

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
