{% set name = "sqlglot" %}
{% set version = "13.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglot-{{ version }}.tar.gz
  sha256: 2df12dc664f343106a4cc33da5894cffe0d8f0a40e3b282b321bf312ef4e4612

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6

test:
  imports:
    - sqlglot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
