{% set name = "sqlglot" %}
{% set version = "16.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglot-{{ version }}.tar.gz
  sha256: 0617c42f7feb1903e028d415aa0f6d5f0e3f53bef3499d09161e3e5f5bb3c1e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - sqlglot
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - openjdk
    - pip
    - pandas
    - pyspark
    - pytest
    - python-dateutil
    - python-duckdb >=0.6

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
