{% set name = "sqlglot" %}
{% set version = "17.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglot-{{ version }}.tar.gz
  sha256: f924f92b24a625485e86511889c3352cfc7ac8b18a15dca9ada58373d4a74b2c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - sqlglot
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - openjdk
    - pip
    - pandas
    - pyspark
    - pytest
    - python-dateutil
    - python-duckdb >=0.6

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
