{% set name = "sqlglot" %}
{% set version = "18.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglot-{{ version }}.tar.gz
  sha256: 5c603a6333e77066514d8a777911c3f052cd9e143c44033d18e2927e07783d8c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm <8.0.1
  run:
    - python >=3.7

test:
  source_files:
    - tests
  imports:
    - sqlglot
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - openjdk
    - pip
    - pandas
    - pyspark
    - pytest
    - python-dateutil
    - python-duckdb >=0.6

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
